### ISSUE TITLE
Trigger manually?

### ISSUE THREAD

**Issue by jchannon** [Decathlon/release-notes-generator-action#14]
With the new action [workflow_dispatch](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/) I can trigger actions manually. Is there a way to pass in a milestone number to the release notes generator action so it generates release notes? Obvioulsy I could re-open then close a milestone but....

**Comment by mmornati** [comment]
Hey. Sorry for the daly but that indeed a good idea.
I'm working on it right now.

**Comment by mmornati** [comment]
PR ready and in review. 
All seems work. If you want to test it before the official release (need to wait for the review) you can doing it in this way:
```
on:
  milestone:
    types: [closed]
  workflow_dispatch:
    inputs:
      milestoneId:
        description: 'Milestone ID'     
        required: true
        default: '1'
name: Milestone Closure
jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create Release Notes
        uses: decathlon/release-notes-generator-action@feat_workflow_dispatch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_FOLDER: temp_release_notes
          USE_MILESTONE_TITLE: "true"
```
