### ISSUE TITLE
PR are not added in the release notes

### ISSUE THREAD

**Issue by rknj** [Decathlon/release-notes-generator-action#35]
I've created a milestone and used it on a couple of already closed PRs.
Then I closed this milestone, which triggered the action.
But, in the logs, I do not see any of the PRs (compared to https://github.com/marketplace/actions/release-notes-generator#result-illustration), only the contributors

Here is the output of the Create Release Notes job:
```
Getting Action Information
Creating release notes for Milestone 1 into the 1.7.0.md file

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.0.RELEASE)

2021-07-02 09:32:55.748  INFO 159 --- [           main] io.spring.releasenotes.Application       : Starting Application v0.0.2 on 3f674ff0de82 with PID 159 (/github-release-notes-generator.jar started by root in /github/workspace)
2021-07-02 09:32:55.770  INFO 159 --- [           main] io.spring.releasenotes.Application       : No active profile set, falling back to default profiles: default
2021-07-02 09:32:56.804  INFO 159 --- [           main] io.spring.releasenotes.Application       : Started Application in 1.654 seconds (JVM running for 2.226)

## :heart: Contributors

We'd like to thank all the contributors who worked on this release!

- [@someone](https://github.com/someone)
```
I've added this action (following https://github.com/marketplace/actions/release-notes-generator#settings-for-v200-release):
```
on: 
  milestone:
    types: [closed]
  workflow_dispatch:
    inputs:
      milestoneId:
        description: 'Milestone ID'     
        required: true
        default: '1'
name: Milestone Closure
jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create Release Notes
      uses: docker://decathlon/release-notes-generator-action:2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OUTPUT_FOLDER: temp_release_notes
        USE_MILESTONE_TITLE: "true"
```
And a section configuration (same as https://github.com/marketplace/actions/release-notes-generator#section-configuration)
And yes I've added "new" and "fix" labels on the PRs
